### ISSUE TITLE
Periodic job not working

### ISSUE THREAD

**Issue by salmancs14** [googlesamples/android-JobScheduler#11]
When I remove my app from the currently running apps list,  then my job service does not show in `adb shell dumpsys jobscheduler` and it stops working periodically.

**Comment by pfmaggi** [comment]
Thanks for reporting this.
I'm closing this issue because this forum is for issues with the codelab.

[Stackoverflow](https://stackoverflow.com/questions/tagged/android-jobscheduler) might be a better forum. Please add information about the device and OS version you're testing this on.

Please reopen if you still think this is an issue with the codelab.
